version: "3"
services:
    app:
        container_name: apiRateLimiter
        restart: always
        build: .
        image: 9993shruti/api_rate_limiter:shruti
        ports: 
            - "3000:3000"
        depends_on:
        - redis
    redis:
        container_name: redis
        image: redis:latest
        ports: 
            - "6380:6380"
        command: ["redis-server", "--bind", "redis", "--port", "6380"]